### ISSUE TITLE
Dnn 'Store Admin' Page does not display for role 'storeadmin'.

### ISSUE THREAD

**Issue by CPQcart** [lepigocher/DNNStore#1] opened 2017-05-01 20:37 UTC
Seeking help as to why Dnn 'Store Admin' Page does not display for role 'storeadmin'.

My CPQcartWizard page/Module works.

How can Module 'Store Admin' On that page be able to work with other than Administrator???

I have at http://test01.cpqcart.com/ two users & Password where you can see the problem.
Post questions or suggestions here or email info (at Sign) myemarketplaces.info
Thanks in advance for any solutions.
Lee

**Comment by lepigocher** [comment] 2017-05-02 12:43
This is by design, only 'SuperUser' accounts or members of the 'Administrators' role group can manage the Store Settings. On the other hand, an administrator can define wich roles can manage orders and catalog (categories and products).
I have defined such kind of settings on your demo site (Module Settings > Permissions > siteadmin, Store Settings > Manage Order > siteadmin, Store Settings > Manage Catalog > siteadmin)

**Comment by CPQcart** [comment] 2017-05-03 01:00
lepigocher:
Thanks for the reply & making the changes to my test site.  I see that Store Admin page displays when logged in as User with role=siteadmin shows with one Menu selection remove ‘Store Info’ which meets my goal (but will be ‘Order’ missing).
I need some more hint as to how this was achieved.  I cannot find a menu ‘Module Settings’ so assume it was done with table modifications.  I have searched in both Dnn Store Doc but could not find anything.  I have reviewed all tables with Modules in it and see 
LastModifiedOnDate with 5-1-17 date in table
Modules, ModulePermission, ModuleDefinitions, & ModuleControls
ModuleSettings no recent LastModifiedOnDate
From the tables indicated above I do not see any Role Name
You indicate
Module Settings > Permissions > siteadmin, 
Store Settings > Manage Order > siteadmin, 
Store Settings > Manage Catalog > siteadmin
So, assume three records are changed but Where?
If this is explained elsewhere please point me to it.
I am not the programmer on this project (use contract people) , just the designer, Inventor of the Patent, & tester.
Thanks, in advance for your help.
Lee

**Comment by lepigocher** [comment] 2017-05-03 01:57
Hi Lee,
All is done using the standard menu and settings!
Connect to your website with the 'admin' account (NOT siteadmin), then clik on the big pencil at the bottom left corner.
Move the mouse above the Store Admin module, a gear icon appears on the top right corner, select Settings in the context menu.
In the opened window, select the second tab (Permissions), here I have just added the group siteadmin with the 'view module' permission. This menu settings is common to all modules Under DNN, sometime you have some settings specific to the module instance in the last tab (after the Page Settings tab)..

**Comment by CPQcart** [comment] 2017-05-04 02:06
Hi lepigocher:
Thanks for the update.
I have setup test02.cpqcart.com different DB like test01.cpqcart.com same users & roles but Store Admin is not displayed.
I cannot see what I am doing different/Wrong.  I have tried on 3 other sites & not displaying.  I had tried this concept before with no results.
Lee

**Comment by lepigocher** [comment] 2017-05-04 06:09
Hi,
You have correctly defined the access right to the module instance BUT you forgot to define the group allowed to manage orders and catalog! Re-read my first response, you have to define "Manage Order" AND "Manage Catalog" settings in the Store Admin module.

**Comment by CPQcart** [comment] 2017-05-04 12:36
Hi lepigocher:
Thank YOU Thank YOU.
I was making a simple task into a Complicated task.
This meets my goals 100%.
Lee

**Comment by lepigocher** [comment] 2017-05-04 14:12
Perfect! :-) I close this issue.

**Closed as completed by lepigocher** 2017-05-04 14:12 UTC
Labels: question
